VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "clsMuft"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public iDiam1 As Integer
Public iDiam2 As Integer

Public pmqty As Integer
Public errs As Integer

Public iType As Integer
Public iMuftType As Integer

Public bByLap As Boolean

Public pointX As Double
Public pointY As Double
Public pointZ As Double

Public sDiam As String
Public sType As String

